### ISSUE TITLE
User Join Error

### ISSUE THREAD

**Issue by msburgess3200** [RathelmMC/MC-Jobs#3]
When any user joins, my logs and console are presented with this...

[21:58:03] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to mcjobs v3.2.0
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:296) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:156) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:817) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: java.lang.NoSuchMethodError: ru.tehkode.permissions.PermissionManager.getUser(Ljava/util/UUID;)Lru/tehkode/permissions/PermissionUser;
    at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getUser(Permission_PermissionsEx.java:243) ~[?:?]
    at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getPlayerGroups(Permission_PermissionsEx.java:252) ~[?:?]
    at net.milkbowl.vault.permission.Permission.getPlayerGroups(Permission.java:696) ~[?:?]
    at com.dmgkz.mcjobs.util.PlayerUtils.getAllowed(PlayerUtils.java:39) ~[?:?]
    at com.dmgkz.mcjobs.playerdata.PlayerCache.verifyPlayerCache(PlayerCache.java:154) ~[?:?]
    at com.dmgkz.mcjobs.listeners.OnPlayerLogins.onPlayerJoin(OnPlayerLogins.java:24) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
    ... 14 more

**Comment by Bl4ckSkull666** [comment]
Kick SimplePluginManager out of your Plugins...

**Comment by msburgess3200** [comment]
I'm not running SimplePluginManager... That's what I checked first.
